#!/usr/bin/env node
/**
 * core/profile-card.js — C2: generate the 2-3KB boot profile card from main/main-memory.md.
 * The card replaces the 80KB main-memory read at boot (once shadow-proven); the full file
 * becomes on-demand episodic archive. Deterministic extraction — same input, same card.
 * USAGE: node core/profile-card.js   → writes system/profile-card.md, prints sizes.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = process.env.CLAUDE_PROJECT_DIR || path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'main', 'main-memory.md');
const OUT = path.join(ROOT, 'meta', 'profile-card.md');

const src = fs.readFileSync(SRC, 'utf8');
const lines = src.split(/\r?\n/);

// extract a section by heading regex, capped at maxLines of CONTENT (skip blanks at edges)
function section(headingRx, maxLines) {
  const start = lines.findIndex(l => headingRx.test(l));
  if (start < 0) return null;
  const level = (lines[start].match(/^#+/) || ['##'])[0].length;
  const out = [];
  for (let i = start + 1; i < lines.length; i++) {
    const m = lines[i].match(/^(#+)\s/);
    if (m && m[1].length <= level) break;
    out.push(lines[i]);
    if (out.filter(l => l.trim()).length >= maxLines) break;
  }
  return out.join('\n').trim();
}

const card = [
  '# Profile Card — generated boot identity (K1/C2)',
  '',
  '_AUTO-GENERATED by `core/profile-card.js` from `main/main-memory.md` — do NOT hand-edit._',
  '_Full identity/history: `main/main-memory.md` (on-demand) · voice/format: `.claude/personality.md`._',
  '',
  '## Who',
  section(/^## Identity & Relationship/, 12) || '(section missing)',
  '',
  '## Etanah quick facts',
  (section(/^## Etanah Quick Reference/, 28) || '(section missing)'),
  '',
  '## みや essentials',
  section(/^### Personal Info/, 14) || '(section missing)',
  '',
  '### Standing rules',
  (src.match(/\*\*Standing Rules:\*\*[\s\S]*?(?=\n###|\n## )/) || ['(missing)'])[0].trim(),
  '',
  '### ADHD accommodations (non-negotiable)',
  section(/^### ADHD Accommodations/, 12) || '(section missing)',
  '',
].join('\n');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, card);
console.log(`profile-card: ${card.length} bytes (source ${src.length} bytes → ${(card.length / src.length * 100).toFixed(1)}%) → system/profile-card.md`);
