#!/usr/bin/env node
/**
 * core/slips.js — C7: slip-log v2. Append-only JSONL + generated dashboard.
 * The 255KB markdown slip-log is FROZEN as archive; "did the guard fire?" becomes a query.
 *
 * USAGE:
 *   node core/slips.js add --category <c> [--qa <QA-n>] [--guard-expected <name>]
 *        [--guard-fired true|false] [--evidence <link/path>] [--action <what>] [--caught-by miya|self|gate]
 *   node core/slips.js dashboard        → regenerates meta/slip-dashboard.md
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = process.env.CLAUDE_PROJECT_DIR || path.resolve(__dirname, '..');
const FILE = path.join(ROOT, 'meta', 'slips.jsonl');
const DASH = path.join(ROOT, 'meta', 'slip-dashboard.md');
const LEGACY = path.join(ROOT, 'meta', 'slip-counts.jsonl');

function arg(name) { const i = process.argv.indexOf('--' + name); return i > 0 ? process.argv[i + 1] : undefined; }
function readJsonl(f) {
  try { return fs.readFileSync(f, 'utf8').split('\n').filter(Boolean).map(l => { try { return JSON.parse(l); } catch (_) { return null; } }).filter(Boolean); }
  catch (_) { return []; }
}

const cmd = process.argv[2];
if (cmd === 'add') {
  const row = {
    ts: new Date().toISOString(),
    type: arg('type') || 'slip', // 'slip' (default) | 'feedback' — preference/praise/style guidance that is NOT a mistake (added 2026-07-19 weekly audit: capture MORE of miya's feedbacks, not only corrections)
    category: arg('category'),
    qa: arg('qa') || null,
    guard_expected: arg('guard-expected') || null,
    guard_fired: arg('guard-fired') === 'true' ? true : (arg('guard-fired') === 'false' ? false : null),
    evidence: arg('evidence') || null,
    // WHY --situation (miya 2026-07-19): rows are written on-the-fly and read weeks later at
    // audit time — evidence says WHAT went wrong, situation says the FRAME (quest/session/phase
    // + trigger). Without it, audit-time refinement reconstructs the frame by guessing — the
    // exact failure that produced implement-from-stale-intent-no-appraise.
    situation: arg('situation') || null,
    action: arg('action') || null,
    caught_by: arg('caught-by') || null,
  };
  if (!row.category) { console.error('slips: --category required'); process.exit(2); }
  fs.appendFileSync(FILE, JSON.stringify(row) + '\n');
  // keep legacy slip-counts.jsonl fed too (other tooling reads it)
  fs.appendFileSync(LEGACY, JSON.stringify({ ts: row.ts, category: row.category }) + '\n');
  console.log('slips: recorded ' + row.category + (row.qa ? ' (' + row.qa + ')' : ''));
  spawnDashboard();
} else if (cmd === 'dashboard') {
  spawnDashboard();
} else {
  console.error('usage: slips <add|dashboard> ...');
  process.exit(2);
}

function spawnDashboard() {
  // DEDUPE on concat (fixed 2026-07-17, みや caught the inflated headline): every slip added
  // since slips.jsonl was born (C7, 2026-07-12) is written to BOTH files by `add` below, so a
  // plain concat counted those rows TWICE — the dashboard read 29 total / 14d 27 when the truth
  // was 16 / 14. LEGACY still contributes its 3 pre-C7 rows, which live nowhere else.
  // Key on ts+category: `add` stamps a fresh ISO ts per row, so collisions are the same row.
  const primary = readJsonl(FILE);
  const seen = new Set(primary.map(r => `${r.ts}|${r.category}`));
  const legacyOnly = readJsonl(LEGACY)
    .filter(r => !seen.has(`${r.ts}|${r.category}`))
    .map(r => ({ ...r, _legacy: true }));
  const allRows = primary.concat(legacyOnly);
  // type split (2026-07-19): 'feedback' rows are preference/praise guidance, NOT mistakes — kept out of slip counts
  const fbRows = allRows.filter(r => r.type === 'feedback');
  const upRows = allRows.filter(r => r.type === 'upgrade'); // system upgrades/refinements — weekly-audit feed (miya 2026-06-20 wider intent + 2026-07-19)
  const rows = allRows.filter(r => r.type !== 'feedback' && r.type !== 'upgrade');
  const fb14 = fbRows.filter(r => Date.parse(r.ts) >= Date.now() - 14 * 86400000);
  const up14 = upRows.filter(r => Date.parse(r.ts) >= Date.now() - 14 * 86400000);
  const d14 = rows.filter(r => Date.parse(r.ts) >= Date.now() - 14 * 86400000);
  const byCat = {};
  for (const r of d14) byCat[r.category] = (byCat[r.category] || 0) + 1;
  const guardRows = d14.filter(r => r.guard_expected != null);
  const miyaCatch = d14.filter(r => r.caught_by === 'miya').length;
  const md = [
    '# Slip Ledger — GENERATED by core/slips.js, never hand-edited',
    '',
    `_${rows.length} total recorded rows · last 14d: ${d14.length} · みや-caught (14d): ${miyaCatch} (north-star: drive to 0)_`,
    '_Historical archive: `meta/slip-log.md` (frozen 2026-07-13) · baseline 2026-07-13: 23 slips/14d, 18 みや-caught_',
    '',
    '## Last 14 days by category',
    '', '| Category | Count |', '|---|---|',
    ...Object.entries(byCat).sort((a, b) => b[1] - a[1]).map(([c, n]) => `| ${c} | ${n} |`),
    '',
    '## Guard accountability (14d rows carrying guard_expected)',
    '', '| ts | category | guard expected | fired? | evidence |', '|---|---|---|---|---|',
    ...guardRows.map(r => `| ${r.ts.slice(0, 10)} | ${r.category} | ${r.guard_expected} | ${r.guard_fired === true ? '✓' : r.guard_fired === false ? '🚨 NO' : '?'} | ${r.evidence || '—'} |`),
    '',
    ...(fb14.length ? [
      '## Feedback (14d — preferences/praise, not mistakes; type=feedback)',
      '', '| ts | category | evidence |', '|---|---|---|',
      ...fb14.map(r => `| ${r.ts.slice(0, 10)} | ${r.category} | ${r.evidence || '—'} |`),
      '',
    ] : []),
    ...(up14.length ? [
      '## System upgrades (14d — refinements/builds shipped; type=upgrade — the weekly-audit feed)',
      '', '| ts | category | evidence |', '|---|---|---|',
      ...up14.map(r => `| ${r.ts.slice(0, 10)} | ${r.category} | ${r.evidence || '—'} |`),
      '',
    ] : []),
  ].join('\n');
  fs.writeFileSync(DASH, md);
  console.log('slips: dashboard regenerated (' + d14.length + ' rows in window)');
}
