#!/usr/bin/env node
// liveness-report — born via forge
// Read-only aggregator: per-component liveness over 4 evidence sources.
//   node lib/liveness-report.js            → writes system/liveness-dashboard.md + console summary
//   node lib/liveness-report.js --summary  → console 1-liner only (boot-friendly), no write
// Sources: .claude/settings.json (registrations, wrap/manifest-aware — same extraction as
// system/sync-hook-catalog.js 2026-08-16 fix) · system/telemetry/hook-fires.jsonl ·
// domain/*/log.jsonl · system/registry.jsonl (lifecycle).
// Flags: REGISTERED component with 0 fires in 30d across BOTH fire-sources → deletion-audit candidate.
// Never deletes anything; evidence only (todo Q1 "Observability-first house-cleaning").
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = process.env.CLAUDE_PROJECT_DIR || path.resolve(__dirname, '..');
const NOW = Date.now();
const WINDOW_MS = 30 * 24 * 3600 * 1000;
const summaryOnly = process.argv.includes('--summary');

function readJsonl(p) {
  try { return fs.readFileSync(p, 'utf8').split('\n').filter(Boolean).map(l => { try { return JSON.parse(l); } catch (_) { return null; } }).filter(Boolean); }
  catch (_) { return []; }
}

// ── 1. registered components (wrap/manifest-aware) ──
const subst = (p) => p.replace(/\$\{CLAUDE_PROJECT_DIR\}/g, ROOT);
const registered = new Map(); // name → {events:Set}
let settings = {};
try { settings = JSON.parse(fs.readFileSync(path.join(ROOT, '.claude', 'settings.json'), 'utf8')); } catch (_) {}
for (const [event, blocks] of Object.entries(settings.hooks || {})) {
  for (const block of blocks || []) {
    for (const h of block.hooks || []) {
      const cmd = h.command || '';
      const wrap = cmd.match(/--wrap\s+"([^"]+\.js)"/);
      const manifest = cmd.match(/--manifest\s+"([^"]+\.json)"/);
      const names = [];
      if (manifest) {
        try { for (const c of (JSON.parse(fs.readFileSync(subst(manifest[1]), 'utf8')).children || [])) names.push(path.basename(c, '.js')); } catch (_) {}
      }
      if (!names.length) {
        const pm = wrap || cmd.match(/"([^"]+\.js)"/) || cmd.match(/(\S+\.js)/);
        if (pm) {
          const base = path.basename(subst(pm[1]));
          if (base !== 'hook-runtime.js' && base !== 'dispatch-hooks.js') names.push(path.basename(base, '.js'));
        }
      }
      for (const n of names) {
        if (!registered.has(n)) registered.set(n, { events: new Set() });
        registered.get(n).events.add(event);
      }
    }
  }
}

// ── 2. telemetry fires ──
const fires = new Map(); // key → {last, count30}
function addFire(key, ts) {
  const t = Date.parse(ts); if (isNaN(t)) return;
  const f = fires.get(key) || { last: 0, count30: 0 };
  if (t > f.last) f.last = t;
  if (NOW - t <= WINDOW_MS) f.count30++;
  fires.set(key, f);
}
for (const r of readJsonl(path.join(ROOT, 'system', 'telemetry', 'hook-fires.jsonl'))) if (r.hook && r.ts) addFire(r.hook, r.ts);

// ── 3. domain logs (fallback fire evidence, keyed by Feature dir name) ──
const domainDir = path.join(ROOT, 'domain');
let features = [];
try { features = fs.readdirSync(domainDir, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name); } catch (_) {}
for (const f of features) for (const r of readJsonl(path.join(domainDir, f, 'log.jsonl'))) if (r.ts) addFire(f, r.ts);

// ── 4. registry lifecycle ──
const lifecycle = new Map();
for (const r of readJsonl(path.join(ROOT, 'system', 'registry.jsonl'))) if (r.name && r.lifecycle) lifecycle.set(r.name, r.lifecycle);

// ── assemble: every registered name + every feature dir ──
const names = new Set([...registered.keys(), ...features]);
const rows = [];
for (const n of [...names].sort()) {
  // fire evidence matches on full registered name OR its feature-dir stem (strip .gate.hook etc.)
  const stem = n.replace(/\.(gate|check|trigger|discipline)?\.?hook$/, '');
  const f = fires.get(n) || fires.get(stem) || { last: 0, count30: 0 };
  const reg = registered.has(n) || registered.has(stem + '.js') ? [...(registered.get(n) || registered.get(stem + '.js') || { events: [] }).events].join('+') : '';
  rows.push({
    name: n,
    registered: reg || (features.includes(n) ? '' : ''),
    lastFire: f.last ? new Date(f.last).toISOString().slice(0, 10) : '—',
    fires30: f.count30,
    lifecycle: lifecycle.get(n) || lifecycle.get(stem) || '—',
    flag: (reg && f.count30 === 0) ? '🚨 0-fire-30d (deletion-audit candidate)' : '',
  });
}

const flagged = rows.filter(r => r.flag);
const summary = `liveness: ${rows.length} components · ${rows.filter(r => r.fires30 > 0).length} fired in 30d · ${flagged.length} registered-but-silent 🚨`;
console.log(summary);
if (summaryOnly) process.exit(0);

const md = [
  '# Component Liveness — GENERATED by lib/liveness-report.js, never hand-edited',
  '',
  `_${summary} · window: 30d · generated from settings.json + telemetry/hook-fires.jsonl + domain/*/log.jsonl + registry.jsonl_`,
  '',
  '| Component | Registered (events) | Last fire | Fires 30d | Lifecycle | Flag |',
  '|---|---|---|---|---|---|',
  ...rows.map(r => `| ${r.name} | ${r.registered || '—'} | ${r.lastFire} | ${r.fires30} | ${r.lifecycle} | ${r.flag} |`),
  '',
  '## Deletion-audit candidates (registered, zero fires in 30d)',
  '',
  ...(flagged.length ? flagged.map(r => `- ${r.name} (${r.registered})`) : ['(none)']),
  '',
  '_Rule: DELETE only with (a) this flag, (b) named successor or reason, (c) rollback line in the commit. A silent component may also mean its trigger never occurred this window — check the trigger before judging._',
].join('\n');
fs.writeFileSync(path.join(ROOT, 'system', 'liveness-dashboard.md'), md);
console.log('written: system/liveness-dashboard.md (' + rows.length + ' rows)');
for (const r of flagged.slice(0, 15)) console.log('  🚨 ' + r.name);
