#!/usr/bin/env python3
"""Generate a COMPLETE per-state DATABASE knowledge file from the LIVE schema.

Writes projects/coding-projects/active/etanah-knowledge/<state>/DATABASE.md with:
  1. Overview (engine/host/schema, table/FK/comment counts, verified date)
  2. Naming divergence vs Melaka — the spine concepts, each state's REAL table + FK column
  3. Prefix legend + per-prefix counts
  4. Spine/anchor tables (real names, existence-verified)
  5. Tugasan census summary (per-urusan tugasan counts, resolved table/columns)
  6. FULL table inventory — EVERY table: name · cols · PK · in/out FK · comment

'Complete' = every table the state's schema holds is listed. Pulled live, nothing assumed.

Usage: python lib/gen_state_knowledge.py --profile wp
"""
import json, sys, argparse, pathlib, datetime
LIB = pathlib.Path(__file__).resolve().parent
ROOT = LIB.parent
sys.path.insert(0, str(LIB))
import pull_schema_live  # type: ignore

KB = pathlib.Path(r"C:\Users\Ridhwan\OneDrive - Pymsoft Sdn Bhd\0. AI\Project-AI-MemoryCore\projects\coding-projects\active\etanah-knowledge")

# spine concepts -> Melaka canonical name, for the divergence table
SPINE = [
    ("application spine", "umm_aplikasi"),
    ("tugasan definition", "ind_tgsn"),
    ("tugasan (app)", "umm_a_tgsn"),
    ("tugasan semasa", "umm_tgsn_semasa"),
    ("langkah", "ind_langkah"),
    ("skrin", "ind_skrin"),
    ("urusan", "ind_ursn"),
    ("hakmilik (app)", "umm_a_hkmlk"),
    ("permohonan tanah", "umm_a_permohonan_tnh"),
    ("pihak berkepentingan", "umm_a_pihak_bkptg"),
    ("pelupusan (app)", "plp_a_pelupusan"),
]
# per-concept candidate real names to probe
CANDIDATES = {
    "umm_aplikasi": ["umm_aplikasi"],
    "ind_tgsn": ["ind_tgsn", "ind_tugasan"],
    "umm_a_tgsn": ["umm_a_tgsn", "umm_a_tugasan"],
    "umm_tgsn_semasa": ["umm_tgsn_semasa", "umm_tugasan_semasa"],
    "ind_langkah": ["ind_langkah"],
    "ind_skrin": ["ind_skrin"],
    "ind_ursn": ["ind_ursn", "ind_urusan"],
    "umm_a_hkmlk": ["umm_a_hkmlk", "umm_a_hakmilik"],
    "umm_a_permohonan_tnh": ["umm_a_permohonan_tnh", "umm_a_permohonan_tanah", "dft_a_permohonan"],
    "umm_a_pihak_bkptg": ["umm_a_pihak_bkptg", "umm_a_pihak_berkepentingan"],
    "plp_a_pelupusan": ["plp_a_pelupusan", "plp_a_pemberimilikan"],
}


def main(profile, label):
    parsed = pull_schema_live.build(profile)  # writes build/schema_parse.json + returns it
    cfg = json.load(open(ROOT / "config" / f"states.{profile}.json", encoding="utf-8"))["connection"]
    names = {t["name"] for t in parsed["tables"]}
    tot = parsed["totals"]

    # divergence: resolve each concept to the state's real table
    div = []
    for concept, mel in SPINE:
        real = next((c for c in CANDIDATES[mel] if c in names), None)
        flag = "" if real == mel else (" ← DIVERGENT" if real else " ← ABSENT")
        div.append((concept, mel, real or "(none found)", flag))

    # prefix counts
    prefixes = parsed.get("group_counts", {})

    # census (if present)
    census_note = ""
    cp = ROOT / "build" / f"tugasan_census.{profile}.json"
    if cp.exists():
        cen = json.load(open(cp, encoding="utf-8"))["tugasans"]
        per = {}
        for t in cen: per[t["urusan"]] = per.get(t["urusan"], 0) + 1
        census_note = " · ".join(f"{k} {v}" for k, v in sorted(per.items())) or "(none)"
        census_total = len(cen)
    else:
        census_total = 0
        census_note = "not pulled"

    today = None
    try:
        import subprocess
        today = subprocess.run(["git", "log", "-1", "--format=%cs"], capture_output=True, text=True).stdout.strip()
    except Exception:
        pass
    today = today or "unknown"

    L = []
    L.append(f"# DATABASE.md — {label}")
    L.append("")
    L.append(f"> **COMPLETE live-schema knowledge for {label}.** Generated by "
             f"`etanah_atlas/lib/gen_state_knowledge.py` from the live database — nothing assumed. "
             f"Every table in the schema is inventoried in §6.")
    L.append(f"> **Engine**: {cfg['engine']} · **Host**: {cfg['host']}:{cfg['port']} · "
             f"**Schema/Owner**: `{cfg['schema']}` · verified {today}")
    L.append("")
    L.append("## 1. Overview")
    L.append("")
    L.append(f"| Metric | Value |")
    L.append("|---|---|")
    L.append(f"| Tables | {tot['tables']} |")
    L.append(f"| Foreign keys | {tot['foreign_keys']} |")
    L.append(f"| Tables with comment | {tot['tables_with_comment']} |")
    L.append(f"| Orphan tables (no FK either way) | {tot['orphan_tables']} |")
    L.append(f"| Tugasan census rows | {census_total} |")
    L.append("")
    L.append("## 2. Naming divergence vs Melaka (spine concepts)")
    L.append("")
    L.append("> The eTanah states mostly share Melaka's table names. Divergences below are REAL "
             "(verified live) — the Atlas resolves them per state; a query written for Melaka will "
             "fail on a DIVERGENT/ABSENT row.")
    L.append("")
    L.append("| Concept | Melaka name | This state's real table | |")
    L.append("|---|---|---|---|")
    for concept, mel, real, flag in div:
        L.append(f"| {concept} | `{mel}` | `{real}` |{flag} |")
    L.append("")
    L.append("## 3. Prefix legend + counts")
    L.append("")
    L.append("| Prefix group | Table count |")
    L.append("|---|---|")
    for p, n in sorted(prefixes.items(), key=lambda x: -x[1]):
        L.append(f"| `{p}` | {n} |")
    L.append("")
    L.append("## 4. Identity anchors (verified live)")
    L.append("")
    L.append("| Anchor | Exists | in-FK | out-FK | cols |")
    L.append("|---|---|---|---|---|")
    for a in parsed.get("identity_anchors", []):
        L.append(f"| `{a['table']}` | {'yes' if a['exists'] else 'NO'} | {a['incoming_fk_count']} | {a['outgoing_fk_count']} | {a['column_count'] if a['column_count'] is not None else '—'} |")
    L.append("")
    L.append("## 5. Tugasan census (Pelupusan urusans)")
    L.append("")
    L.append(f"Per-urusan tugasan counts (live): {census_note}")
    L.append("")
    L.append(f"## 6. FULL table inventory ({tot['tables']} tables)")
    L.append("")
    L.append("> Every table in the schema. `PK` = primary-key column(s); `in/out` = incoming / "
             "outgoing FK counts.")
    L.append("")
    L.append("| Table | cols | PK | in | out | comment |")
    L.append("|---|---|---|---|---|---|")
    for t in parsed["tables"]:
        pk = ", ".join(t.get("pk", [])) or "—"
        cm = (t.get("comment") or "").replace("|", "\\|").replace("\n", " ")[:120]
        L.append(f"| `{t['name']}` | {t['column_count']} | {pk} | {t['incoming_fk_count']} | {t['outgoing_fk_count']} | {cm} |")
    L.append("")
    L.append(f"*Generated {today} from live {cfg['engine']} schema `{cfg['schema']}`. "
             f"Regenerate: `python etanah_atlas/lib/gen_state_knowledge.py --profile {profile} --label \"{label}\"`.*")

    out_dir = KB / profile
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "DATABASE.md").write_text("\n".join(L), encoding="utf-8")
    print(f"[knowledge] {label}: {tot['tables']} tables, {len([d for d in div if d[3]])} divergences -> {out_dir / 'DATABASE.md'}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--profile", required=True); ap.add_argument("--label", required=True)
    a = ap.parse_args(); main(a.profile, a.label)
